apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: dapr-components
spec:
  type: state.postgresql
  version: v1
  metadata:
    - name: connectionString
      value: "host=yb-tservers.yugabyte.svc.cluster.local port=5433 user=yugabyte password=yugabyte dbname=yugabyte" # Default user, password, dbname